---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: 
      - htop
      - tmux
      - vim-nox  
      - python3-psutil
        
  - name: copy wallpaper file
     copy: 
       src: files/wallpaper.png
       dest: /usr/share/backgrounds/ansible-wallpaper.png
       owner: root
       group: root

  - name: set wallpaper
     become_user: whenrick	
     dconf:
       key: "/org/gmome/desktop/background/picture-uri"
       value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpaper position
     become_user: whenrick
     dconf:
       key: "/org/gmome/desktop/background/picture-options"
       value: "'zoom'"



  
